### ISSUE TITLE
Package Reexport not found in current path

### ISSUE THREAD

**Issue by kescobo** [tlienart/Xranklin.jl#241]
```
julia> Xranklin.serve()
ERROR: LoadError: ArgumentError: Package Reexport not found in current path.
- Run `import Pkg; Pkg.add("Reexport")` to install the Reexport package.
```

<details>
<summary><b>Full stack trace</b></summary>

```
LoadError: ArgumentError: Package Reexport not found in current path.
- Run `import Pkg; Pkg.add("Reexport")` to install the Reexport package.
Stacktrace:
  [1] macro expansion
    @ ./loading.jl:1630 [inlined]
  [2] macro expansion
    @ ./lock.jl:267 [inlined]
  [3] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1611
  [4] eval
    @ ./boot.jl:370 [inlined]
  [5] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1903
  [6] include_string (repeats 2 times)
    @ ./loading.jl:1913 [inlined]
  [7] modules_setup(c::Xranklin.GlobalContext{Xranklin.LocalContext})
    @ Xranklin ~/.julia/dev/Xranklin/src/context/code/modules.jl:269
  [8] Xranklin.GlobalContext(vars::Dict{Symbol, Any}, defs::Dict{String, Xranklin.LxDef}; alias::Dict{Symbol, Symbol})
    @ Xranklin ~/.julia/dev/Xranklin/src/context/context.jl:174
  [9] GlobalContext
    @ ~/.julia/dev/Xranklin/src/context/context.jl:127 [inlined]
 [10] DefaultGlobalContext()
    @ Xranklin ~/.julia/dev/Xranklin/src/context/default_context.jl:205
 [11] serve(d::String; dir::String, folder::String, clear::Bool, final::Bool, single::Bool, eval::Bool, nocode::Bool, threads::Bool, use_threads::Bool, prepath::String, prefix::String, base_url_prefix::String, allow_no_index::Bool, debug::Bool, cleanup::Bool, skip::Vector{String}, port::Int64, host::String, launch::Bool)
    @ Xranklin ~/.julia/dev/Xranklin/src/build/serve.jl:104
 [12] serve
    @ ~/.julia/dev/Xranklin/src/build/serve.jl:58 [inlined]
 [13] serve()
    @ Xranklin ~/.julia/dev/Xranklin/src/build/serve.jl:58
 [14] top-level scope
    @ REPL[1]:1
```

</details>

I can't quite sort this out, since Reexport is obviously in the Project.toml (I've got Xranklin dev'd, and did a resolve / instantiate etc).

And if I add Reexport to my website Project.toml, it works fine.

**Comment by tlienart** [comment]
Thanks @kescobo the next commit will fix this; sorry there's some heavy lifting going on with Xranklin with the inevitable introduction of dumb bugs. Glad that you're giving it a shot though.

(you can remove Reexport from your Project toml after getting the latest commit)

**Comment by tlienart** [comment]
for the sake of clarity, the use of Reexport goes as follows:

every `.md` page in Xranklin basically corresponds to two notebooks: one for page variables, and one with all the code cells that you might have on a page. They both behave differently, they're just kept separate since their purpose are different.

The "module" structure of these notebooks is as follows:

```
module Page
  module FranklinCore
  end
  module Utils
  end
end
```

When you evaluate a code cell, it gets evaluated in the `Page` module. The `Page` module has access to `Utils` which is where all of the `utils.jl` stuff gets evaluated. the `FranklinCore` should not be directly used by the user but provides a few core tools that `Utils` pulls in that can make writing utils functions easier (e.g. `locvar(...)`).

With this context in mind, if you want a page to run a cell like this:

````
```>
Date(2023,7,25)
```
````

the module `Page` should load `Dates` so that a bare "unqualified" `Date` can be called. Of course you could have done `using Dates; Date...` in the cell and that would have worked fine. But it's clear that user would expect to be able to define packages that they could use *across* pages.

To do so, you have to load the package in your `utils.jl` file with `@reexport`:

`utils.jl`:
```
@reexport using Dates # now all pages work as if they loaded Dates
```

I hope this makes sense.
