### ISSUE TITLE
Posts failing to gather into respective tags

### ISSUE THREAD

**Issue by luraess** [tlienart/Xranklin.jl#275]
Following up on #273 remaining specific issues.

> So it seems that an issue with tags is your remaining issue, to help you with it, it would help a lot if you first verified that the `__site/tags/` folder are appropriately filled upon site generation. I.e. do `serve(clear=true, single=true)` then go to `__site/tags/` and check that there's everything there you might expect. If not, then that's the issue. If so, then the issue is with your `hfun`.

Checking on that, I have a folder per tag in `__site/tags/` however the `index.html` does not list the posts referring to the specific tag; there is only `Tags: <tagname>` (empty list).

**Comment by tlienart** [comment]
could you put your code on a sandbox repository so I can see this directly?

On your public repo I can see that `news` seems to work fine as per: https://github.com/Unil-SGC/unil-sgc.github.io/blob/d597b8bc5783152370c2e4be02386eb46da75e90/tags/news/index.html#L123 but I imagine that's not your issue.

**Comment by luraess** [comment]
I've put a sandbox repo here https://github.com/Unil-SGC/multipost.

I guess the issue is that I was playing with the multi-post handling on a branch, and thus the link you are referring to in your previous comment does not show the issue as it points to the current standard Xranklin website which does not contains multiple post folders.

So, the issue is that with the current implementation trying to handle multiple posts, clicking on a tag would not list any posts which relate to this tag. The example with the `news` tag shows an empty listing here https://github.com/Unil-SGC/multipost/blob/cea2830c233c72e25f5bb27b1a072386668f98c7/tags/news/index.html#L120

**Comment by luraess** [comment]
Following up on that thread. In my sandbox repo, I've added manually the two folder names in which I want the post-logic to happen, `news` and `events`. This works fine.

The remaining is that if the folder containing the posts is not called `posts`, then listing tags returns empty list; when clicking on a tag in a post, the page opened which should list all posts containing the same tag is empty, e.g.  https://unil-sgc.github.io/multipost/tags/event/, which related to following code https://github.com/Unil-SGC/multipost/blob/499b372662789ffb991e0f57160471549f7239b6/tags/event/index.html#L119.

It seems that the `{{taglist}}` `hfun` returns an empty string here https://github.com/Unil-SGC/multipost/blob/ebca8f3635616656233a09bc62c45ad6ef621cd8/utils.jl#L37 while it shouldn't. One potential cause may be the early return statement here https://github.com/Unil-SGC/multipost/blob/ebca8f3635616656233a09bc62c45ad6ef621cd8/utils.jl#L51 which should not be called all the time.

I could however not debug really further. Do you see what could still go wrong? Thanks

**Comment by tlienart** [comment]
Apologies for taking so long to reply.

If you put `@show get_rpath()` and `@show geltvar(:tag_name)` in `hfun_taglist` like

```julia
function hfun_taglist()
    @show get_rpath()
    @show getlvar(:tag_name)
    return hfun_list_posts(getlvar(:tag_name))
end
```

then run `serve` I think you'll see what's going on:

```bash
[ Info: > Full Pass [MD/I] (sequential)
get_rpath() = "tags/event/index.html"
getlvar(:tag_name) = "Event"
get_rpath() = "tags/julia/index.html"
getlvar(:tag_name) = "Julia"
get_rpath() = "tags/geocomputing_coffee/index.html"
getlvar(:tag_name) = "Geocomputing-coffee"
```

this is not executed from the actual pages defining the tags, it's executed from the tag pages themselves. I need to explain a bit of how Xranklin works so that this can make some sense. I also realise that I probably led you astray before, sorry about that.

### How the sausage works

Let's say you have a page at path `foo/bar.md` and it defines two tags `tags = ["t1", "t2"]`. 

When Xranklin parses `foo/bar.md`, it has a `LocalContext` object associated with that page which keeps track, among other things, of the tags of that page. So after parsing the page, that `LocalContext` stores the tags associated with the page `t1`, `t2`

When it comes to writing tag pages (i.e. pages in `tags/...`) Xranklin creates a LocalContext per tag page which stores the tag name (`getlvar(:tag_name)`). That LocalContext allows it to resolve the HTML associated with the tag template.

### What you want

I'll focus on what you want and how to get there rather than pointing out what doesn't work as that should come naturally as a an aside.

The `{{taglist}}` is part of your tag template, which means it's resolved then. For the tag page associated with tag `t1`, you want to get the list of pages that have `t1` in their `tags`. 

The *GlobalContext* has all of the `LocalContext` associated with every page. So if you loop over that, you can check:

```julia
# e.g. in body of taglist
current_tag = getlvar(:tag_name) # associated with the tag-page local context
# let's find all page contexts which define the tag:
for (page_rpath, page_lc) in cur_gc().children_contexts
    page_tags = get_page_tags(page_lc) # this is a dictionary with entries {tag_id => tag_name}
    if current_tag in values(page_tags)
        # page at page_rpath is connected to the tag
        # here put the logic to write an item listing that page 
    end
end
```

let's try to get a version what you had going

```julia
function hfun_taglist()
    current_tag = getlvar(:tag_name)

    connected_rps = [
        rpi
        for (rpi, lci) in cur_gc().children_contexts
        if current_tag in values(get_page_tags(lci))
    ]
    posts = [
        (
            date  = getvarfrom(:date, rp),
            title = getvarfrom(:title, rp),
            href  = "/$(splitext(rp)[1])",
            tags  = get_page_tags(rp)
        )
        for rp in connected_rps
    ]

    return string(
        node("ul",
            (
                node("li",
                    node("span", class="date", Dates.format(p.date, "U d, yyyy") * "  — "),
                    node("a", class="title", href=p.href, p.title)
                )
                for p in posts
            )...
        )
    )
end
```

sure enough that seems to work:

![Screenshot 2023-11-30 at 23 01 51](https://github.com/tlienart/Xranklin.jl/assets/10897531/fc24eadb-41b9-47bd-a6f5-6afa7823ae3d)

![Screenshot 2023-11-30 at 23 02 30](https://github.com/tlienart/Xranklin.jl/assets/10897531/a25bdb5a-49ef-490e-8dd7-f1dde4041b76)

you'll have to fix the CSS but that should be easy enough. Hope that addresses your problem and sorry again if my initial answers led you astray... ! (and thanks for not giving up)

**Comment by luraess** [comment]
Thanks so much for taking the time to dive into the details! That was helpful 🙏 

The Tag page style is also now fixed:

![Screenshot 2023-12-01 at 08 32 06](https://github.com/tlienart/Xranklin.jl/assets/61313342/52631a8b-45ae-4b3b-ac13-14f508b64dcb)

Which is now reflected in the actual (non-sandbox) website https://unil-sgc.github.io/events/ (for the record).

**Comment by tlienart** [comment]
awesome
