### ISSUE TITLE
Adjusting CSS leads to MethodError: no method matching _memcmp(::Vector{UInt8}, ::Vector{UInt8}, ::Int64)

### ISSUE THREAD

**Issue by kescobo** [tlienart/Xranklin.jl#277]
Restarting the server reloads fine.

**Comment by tlienart** [comment]
Can you check that you've got the latest commit?

This memcmp thing is a change in internal Julia stuff in 1.9 iirc, and so there's a commit on xranklin that checks which version you're on and whether to use one or the other.

This memcmp is used in order to do a quick and dirty comparison between two files following a suggestion by Steven Johnson a few years ago on discourse. It just needed to be adapted given it relied on this internal function :)

**Comment by kescobo** [comment]
Odd - `] st` said I was on `#main`, and `] up` didn't do anything, but when I added `251d105` explicitly, it worked. And then adding `#main` again also worked. Sorry for the noise!
